//Éste es el contenedor de toda la App

// export const metadata = {
//   	title: 'Next.js',
//   	description: 'Generated by Next.js',
// }

import Navbar from "../components/Navbar";
import { Roboto } from "next/font/google";	//Para importar diferentes tipos de letra
import "./globals.css";

export const metadata = {
	title: "My tienda con Next.js",
	description: "Esta es la página principal de mi tienda",
	keywords: "tienda, online, ecommerce"
}

const roboto = Roboto({
	weight: ["300", "400", "500", "700"],
	styles: ["italic", "normal"],
	subsets: ["latin"]
})

export default function RootLayout({ children }) {
  return (
	//La etiqueta html solo se crea en el layout inicial
    <html lang="en">
		{/* 
		Esto no es necesario porque Next.js lo agrega con metadata
		<head>
			<title>My App</title>
		</head> 
		*/}
      	<body className={ roboto.className }>
			<Navbar />
			{children}
		</body>
    </html>
  )
}
